{
 "title": "GameVault Observabilidad",
 "tags": [
  "gamevault",
  "proyecto-3"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Throughput API",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(gamevault_api_requests_total[1m]))",
     "legendFormat": "requests/s"
    }
   ]
  },
  {
   "title": "Latencia promedio",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(gamevault_api_request_latency_seconds_sum[1m])) / sum(rate(gamevault_api_request_latency_seconds_count[1m]))",
     "legendFormat": "latencia promedio"
    }
   ]
  },
  {
   "title": "Gauge: videojuegos registrados",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "gamevault_videojuegos_total", "legendFormat": "videojuegos" }
   ]
  }
 ]
}